UPDATE configs 
SET config = '{
  "msv": {
    "mission": "frozon",
    "site": "",
    "masterdb": false,
    "view": ["-150", "75", "4"],
    "radius": {"major": 6371008, "minor": 6371008},
    "mapscale": ""
  },
  "projection": {
    "custom": false,
    "epsg": "",
    "proj": "4326",
    "globeproj": "webmercator",
    "xmlpath": "",
    "bounds": ["-180", "60", "180", "90"],
    "origin": ["", ""],
    "reszoomlevel": "",
    "resunitsperpixel": ""
  },
  "look": {
    "pagename": "Frozon Arctic Research",
    "minimalist": false,
    "topbar": true,
    "toolbar": true,
    "scalebar": true,
    "coordinates": true,
    "zoomcontrol": false,
    "graticule": true,
    "miscellaneous": true,
    "bodycolor": "",
    "topbarcolor": "",
    "toolbarcolor": "",
    "mapcolor": "",
    "swap": true,
    "copylink": true,
    "screenshot": true,
    "fullscreen": true,
    "help": true,
    "logourl": "",
    "helpurl": ""
  },
  "panelSettings": {},
  "panels": {"viewer": true, "map": true, "globe": true},
  "time": {"enabled": true},
  "tools": [
    {"name": "Layers", "icon": "layers", "js": "LayersTool"},
    {"name": "Legend", "icon": "format-list-bulleted-type", "js": "LegendTool"},
    {"name": "Info", "icon": "information-variant", "js": "InfoTool"}
  ],
  "layers": [
    {
      "name": "OSM_Basemap",
      "uuid": "439c88fe-91ee-40a4-b59b-fc90c10586aa",
      "sublayers": [],
      "type": "tile",
      "visibility": true,
      "sourceType": "url",
      "url": "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
      "tileformat": "wmts",
      "controlled": true,
      "initialOpacity": 1,
      "minZoom": 2,
      "maxNativeZoom": 19,
      "maxZoom": 19,
      "throughTileServer": false,
      "cogResampling": "nearest",
      "cogTransform": false,
      "cogColormap": "viridis",
      "demparser": "rgba",
      "style": {"brightness": 1, "contrast": 1, "saturation": 1, "blend": "none"},
      "time": {"enabled": false, "type": "requery", "compositeTile": false, "refreshIntervalEnabled": false}
    },
    {
      "name": "Areas_of_Interest",
      "uuid": "b3c4d5e6-7f8g-9h0i-1j2k-345678901fed",
      "sublayers": [],
      "type": "vector",
      "visibility": true,
      "sourceType": "url",
      "url": "Missions/frozon/Layers/Frozon_Areas_of_Interest.geojson",
      "controlled": true,
      "initialOpacity": 1,
      "minZoom": 0,
      "maxZoom": 18,
      "style": {"color": "#ff6b35", "opacity": 1, "fillColor": "#ff6b35", "fillOpacity": 0.3, "weight": 3, "radius": 8},
      "time": {"enabled": false, "type": "requery", "refreshIntervalEnabled": false},
      "variables": {
        "dynamicExtent": false,
        "noDuplicates": false,
        "getFeaturePropertiesOnClick": true,
        "style": {"nointeraction": false}
      }
    },
    {
      "name": "Polar_Countries",
      "uuid": "c4d5e6f7-8g9h-0i1j-2k3l-456789012gfe",
      "sublayers": [],
      "type": "vector",
      "visibility": true,
      "sourceType": "url",
      "url": "Missions/frozon/Layers/Frozon_PolarCountries.geojson",
      "controlled": true,
      "initialOpacity": 1,
      "minZoom": 0,
      "maxZoom": 18,
      "style": {"color": "#64748b", "opacity": 0.8, "fillColor": "#64748b", "fillOpacity": 0.15, "weight": 2},
      "time": {"enabled": false, "type": "requery", "refreshIntervalEnabled": false},
      "variables": {
        "dynamicExtent": false,
        "noDuplicates": false,
        "getFeaturePropertiesOnClick": true,
        "style": {"nointeraction": false}
      }
    },
    {
      "name": "SWOT_Freeboard_530",
      "uuid": "f1e2d3c4-5a6b-7c8d-9e0f-123456789abc",
      "sublayers": [],
      "type": "data",
      "visibility": false,
      "sourceType": "url",
      "url": "Missions/frozon/Layers/Freeboard/SWOT_L2_LR_NPFRB_024_530_20241201T002652_20241201T011735_PIC2_01_freeboard_COG.tif",
      "tileformat": "cog",
      "controlled": true,
      "initialOpacity": 0.8,
      "minZoom": 1,
      "maxNativeZoom": 12,
      "maxZoom": 14,
      "throughTileServer": true,
      "cogResampling": "bilinear",
      "cogTransform": false,
      "cogColormap": "plasma",
      "demparser": "rgba",
      "style": {"brightness": 1, "contrast": 1.2, "saturation": 1.1, "blend": "none"},
      "time": {"enabled": false, "type": "requery", "compositeTile": false, "refreshIntervalEnabled": false}
    }
  ]
}',
version = version + 1
WHERE mission = 'frozon' AND id = (SELECT MAX(id) FROM configs WHERE mission = 'frozon');